##===- source/Host/netbsd/Makefile --------------------------*- Makefile -*-===##
# 
#                     The LLVM Compiler Infrastructure
#
# This file is distributed under the University of Illinois Open Source
# License. See LICENSE.TXT for details.
# 
##===----------------------------------------------------------------------===##

LLDB_LEVEL := ../../..
LIBRARYNAME := lldbHostNetBSD
BUILD_ARCHIVE = 1

CPP.Flags += -I/usr/pkg/include

include $(LLDB_LEVEL)/Makefile
